name: Craftgate Dotnet CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-18.04

    name: Dotnet Build & Test
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup dotnet 1.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '1.1.x'
        
      - name: Setup dotnet 2.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.0.x'
        
      - name: Setup dotnet 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
  

        
      - run: dotnet build -c Release ./Craftgate
      - run: dotnet test Test -f netcoreapp1.1
      - run: dotnet test Test -f netcoreapp2.0
      - run: dotnet test Test -f netcoreapp3.1
