name: Craftgate Dotnet Client Release

on:
  release:
    types: [published]

jobs:
  pack:
    name: Release Library
    runs-on: windows-2022
    steps:
      - name: Install .net framework 4.5 SDK
        shell: pwsh
        run: |
          echo "download ${env:net45SdkUrl}"
          Invoke-WebRequest -Uri "${env:net45SdkUrl}" -OutFile "${env:temp}\net45sdk.zip"
          echo "unzip net45sdk.zip"
          Expand-Archive -Force -LiteralPath "${env:temp}\net45sdk.zip" -DestinationPath "${env:temp}\net45sdk"
          echo "delete ${env:sdkSystemPath}\v4.5"
          [IO.Directory]::Delete("${env:sdkSystemPath}\v4.5", $True)
          echo "move SDK to ${env:sdkSystemPath}\v4.5"
          Move-Item -Force -LiteralPath "${env:temp}\net45sdk\build\.NETFramework\v4.5" -Destination "${env:sdkSystemPath}"
          
      - uses: actions/checkout@v2

      - name: Setup dotnet 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_SECRET_KEY}}

      - name: Set Package Version
        run: echo ("PACKAGE_VERSION=" + $env:GITHUB_REF.replace('refs/tags/', '')) >> $env:GITHUB_ENV 
    
      - name: Pack Client Library
        run: dotnet pack -c Release -p:PackageVersion="${{ env.PACKAGE_VERSION }}" ./Craftgate

      - name: Push Packed Client Library to Nuget
        run:  dotnet nuget push ./Craftgate/bin/Release/Craftgate.${{ env.PACKAGE_VERSION }}.nupkg -k $env:NUGET_SECRET_KEY
        env: 
          NUGET_SECRET_KEY: ${{secrets.NUGET_SECRET_KEY}}
