name: Craftgate Dotnet Client Release

on:
  release:
    types: [published]

jobs:
  pack:
    name: Release Library
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_SECRET_KEY}}
          
      - name: Install .NET Framework 4.5 Developer Pack (manual)
        run: |
          Invoke-WebRequest -Uri "https://download.visualstudio.microsoft.com/download/pr/6f6b3d6a-6f3b-4b1e-8e4a-9d8ef4f4b9a6/1b1e7f2b2bb6ec9a9e9b8d6e40f7b2a2/ndp45-devpack-enu.exe" -OutFile NDP45-DevPack.exe
          Start-Process -FilePath .\NDP45-DevPack.exe -ArgumentList "/quiet" -Wait
        if: runner.os == 'Windows'
      
      - name: Set Package Version
        run: echo ("PACKAGE_VERSION=" + $env:GITHUB_REF.replace('refs/tags/', '')) >> $env:GITHUB_ENV 
    
      - name: Pack Client Library
        run: dotnet pack -c Release -p:PackageVersion="${{ env.PACKAGE_VERSION }}" ./Craftgate

      - name: Push Packed Client Library to Nuget
        run:  dotnet nuget push ./Craftgate/bin/Release/Craftgate.${{ env.PACKAGE_VERSION }}.nupkg -k $env:NUGET_SECRET_KEY
        env: 
          NUGET_SECRET_KEY: ${{secrets.NUGET_SECRET_KEY}}
