name: Craftgate Dotnet CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-2022

    name: Dotnet Build & Test
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet 1.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '1.1.x'

      - name: Setup dotnet 2.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.0.x'

      - name: Setup dotnet 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          
      - name: Install .NET Framework 4.5 Developer Pack (manual)
        run: |
          Invoke-WebRequest -Uri "https://download.microsoft.com/download/1/5/B/15B23482-DBD5-4E7B-BCB0-9E7B9D2D7C50/NDP45-DevPack-KB2872776-ENU.exe" -OutFile NDP45-DevPack.exe
          Start-Process -FilePath .\NDP45-DevPack.exe -ArgumentList "/quiet" -Wait
        if: runner.os == 'Windows'       

      - run: dotnet build -c Release ./Craftgate
      - run: dotnet test Test -f netcoreapp1.1
      - run: dotnet test Test -f netcoreapp2.0
      - run: dotnet test Test -f netcoreapp3.1
      - run: dotnet test Test -f net45
      - run: dotnet test Test -f net462
