using System.Runtime.Serialization;

namespace Craftgate.Model
{
    public enum ApmType
    {
        [EnumMember(Value = "PAPARA")] PAPARA,
        [EnumMember(Value = "PAYONEER")] PAYONEER,
        [EnumMember(Value = "SODEXO")] SODEXO,
        [EnumMember(Value = "SODEXO_GIFT")] SODEXO_GIFT,
        [EnumMember(Value = "EDENRED")] EDENRED,
        [EnumMember(Value = "EDENRED_GIFT")] EDENRED_GIFT,
        [EnumMember(Value = "ALIPAY")] ALIPAY,
        [EnumMember(Value = "PAYPAL")] PAYPAL,
        [EnumMember(Value = "KLARNA")] KLARNA,
        [EnumMember(Value = "AFTERPAY")] AFTERPAY,
        [EnumMember(Value = "APPLEPAY")] APPLEPAY,
        [EnumMember(Value = "GOOGLEPAY")] GOOGLEPAY,
        [EnumMember(Value = "HEPSIPAY_WALLET")] HEPSIPAY_WALLET,
        [EnumMember(Value = "HEPSIPAY_FINANCE")] HEPSIPAY_FINANCE,
        [EnumMember(Value = "HEPSIPAY_SHOPPING_LOAN")] HEPSIPAY_SHOPPING_LOAN,
        [EnumMember(Value = "STRIPE")] STRIPE,
        [EnumMember(Value = "KASPI")] KASPI,
        [EnumMember(Value = "INSTANT_TRANSFER")] INSTANT_TRANSFER,
        [EnumMember(Value = "MASLAK")] MASLAK,
        [EnumMember(Value = "TOMPAY")] TOMPAY,
        [EnumMember(Value = "TOM_FINANCE")] TOM_FINANCE,
        [EnumMember(Value = "PAYCELL")] PAYCELL,
        [EnumMember(Value = "ALFABANK")] ALFABANK,
        [EnumMember(Value = "ZIP")] ZIP,
        [EnumMember(Value = "HASO")] HASO,
        [EnumMember(Value = "KARACA_FINANS")] KARACA_FINANS,
        [EnumMember(Value = "CHIPPIN")] CHIPPIN,
        [EnumMember(Value = "MULTINET")] MULTINET,
        [EnumMember(Value = "MULTINET_GIFT")] MULTINET_GIFT,
        [EnumMember(Value = "MULTINET_NEO_GIFT")] MULTINET_NEO_GIFT,
        [EnumMember(Value = "FUND_TRANSFER")] FUND_TRANSFER,
        [EnumMember(Value = "CASH_ON_DELIVERY")] CASH_ON_DELIVERY,
        [EnumMember(Value = "ISPAY")] ISPAY,
        [EnumMember(Value = "PAYMOB")] PAYMOB,
        [EnumMember(Value = "METROPOL")] METROPOL,
        [EnumMember(Value = "VODAFONE_DCB")] VODAFONE_DCB,
        [EnumMember(Value = "BIZUM")] BIZUM,
        [EnumMember(Value = "PAYLANDS_MB_WAY")] PAYLANDS_MB_WAY,
        [EnumMember(Value = "IWALLET")] IWALLET,
        [EnumMember(Value = "SETCARD")] SETCARD,
        [EnumMember(Value = "PAYCELL_DCB")] PAYCELL_DCB,
        [EnumMember(Value = "PAPEL")] PAPEL
    }
}