using System.Runtime.Serialization;

namespace Craftgate.Model
{
    public enum PaymentProvider
    {
        [EnumMember(Value = "BANK")] BANK,
        [EnumMember(Value = "CG_WALLET")] CG_WALLET,
        [EnumMember(Value = "MASTERPASS")] MASTERPASS,
        [EnumMember(Value = "GARANTI_PAY")] GARANTI_PAY,
        [EnumMember(Value = "YKB_WORLD_PAY")] YKB_WORLD_PAY,
        [EnumMember(Value = "YKB_WORLD_PAY_SHOPPING_LOAN")] YKB_WORLD_PAY_SHOPPING_LOAN,
        [EnumMember(Value = "PAPARA")] PAPARA,
        [EnumMember(Value = "PAYONEER")] PAYONEER,
        [EnumMember(Value = "SODEXO")] SODEXO,
        [EnumMember(Value = "EDENRED")] EDENRED,
        [EnumMember(Value = "TOKENFLEX")] TOKENFLEX,
        [EnumMember(Value = "METROPOL")] METROPOL,
        [EnumMember(Value = "IWALLET")] IWALLET,
        [EnumMember(Value = "ALIPAY")] ALIPAY,
        [EnumMember(Value = "PAYPAL")] PAYPAL,
        [EnumMember(Value = "KLARNA")] KLARNA,
        [EnumMember(Value = "AFTERPAY")] AFTERPAY,
        [EnumMember(Value = "APPLEPAY")] APPLEPAY,
        [EnumMember(Value = "GOOGLEPAY")] GOOGLEPAY,
        [EnumMember(Value = "HEPSIPAY")] HEPSIPAY,
        [EnumMember(Value = "STRIPE")] STRIPE,
        [EnumMember(Value = "KASPI")] KASPI,
        [EnumMember(Value = "INSTANT_TRANSFER")] INSTANT_TRANSFER,
        [EnumMember(Value = "MASLAK")] MASLAK,
        [EnumMember(Value = "TOMPAY")] TOMPAY,
        [EnumMember(Value = "TOM_FINANCE")] TOM_FINANCE,
        [EnumMember(Value = "ALFABANK")] ALFABANK,
        [EnumMember(Value = "ZIP")] ZIP,
        [EnumMember(Value = "KARACA_FINANS")] KARACA_FINANS,
        [EnumMember(Value = "HASO")] HASO,
        [EnumMember(Value = "PAYCELL")] PAYCELL,
        [EnumMember(Value = "MULTINET")] MULTINET,
        [EnumMember(Value = "CHIPPIN")] CHIPPIN,
        [EnumMember(Value = "ISPAY")] ISPAY,
        [EnumMember(Value = "PAYMOB")] PAYMOB,
        [EnumMember(Value = "VODAFONE")] VODAFONE,
        [EnumMember(Value = "BIZUM")] BIZUM,
        [EnumMember(Value = "PAYLANDS_MB_WAY")] PAYLANDS_MB_WAY,
        [EnumMember(Value = "SETCARD")] SETCARD,
        [EnumMember(Value = "PAPEL")] PAPEL,
        [EnumMember(Value = "BKM_EXPRESS")] BKM_EXPRESS,
        [EnumMember(Value = "OFFLINE")] OFFLINE
    }
}