using System.Runtime.Serialization;

namespace Craftgate.Model
{
    public enum PosIntegrator
    {
        [EnumMember(Value = "ADYEN")] ADYEN,
        [EnumMember(Value = "AKBANK")] AKBANK,
        [EnumMember(Value = "AKBANK_VPOS")] AKBANK_VPOS,
        [EnumMember(Value = "ALGORITMA")] ALGORITMA,
        [EnumMember(Value = "ANADOLUBANK")] ANADOLUBANK,
        [EnumMember(Value = "BIRLESIK_ODEME")] BIRLESIK_ODEME,
        [EnumMember(Value = "BRAINTREE")] BRAINTREE,
        [EnumMember(Value = "CHECKOUT")] CHECKOUT,
        [EnumMember(Value = "DENIZBANK")] DENIZBANK,
        [EnumMember(Value = "ELEKSE")] ELEKSE,
        [EnumMember(Value = "FIBABANK")] FIBABANK,
        [EnumMember(Value = "FIBABANK_ASSECO")] FIBABANK_ASSECO,
        [EnumMember(Value = "FINANSBANK")] FINANSBANK,
        [EnumMember(Value = "FINANSKATILIM")] FINANSKATILIM,
        [EnumMember(Value = "GARANTI")] GARANTI,
        [EnumMember(Value = "HALKBANK")] HALKBANK,
        [EnumMember(Value = "HALKBANK_VPOS")] HALKBANK_VPOS,
        [EnumMember(Value = "HALKODE")] HALKODE,
        [EnumMember(Value = "HALYKBANK")] HALYKBANK,
        [EnumMember(Value = "INGBANK")] INGBANK,
        [EnumMember(Value = "ISBANK")] ISBANK,
        [EnumMember(Value = "ISBANK_VPOS")] ISBANK_VPOS,
        [EnumMember(Value = "IYZICO")] IYZICO,
        [EnumMember(Value = "KUVEYTTURK")] KUVEYTTURK,
        [EnumMember(Value = "MOKA")] MOKA,
        [EnumMember(Value = "MONEYPAY")] MONEYPAY,
        [EnumMember(Value = "NKOLAY")] NKOLAY,
        [EnumMember(Value = "NUVEI")] NUVEI,
        [EnumMember(Value = "PAPEL")] PAPEL,
        [EnumMember(Value = "PARAM_POS")] PARAM_POS,
        [EnumMember(Value = "PAYBYME")] PAYBYME,
        [EnumMember(Value = "PAYCELL")] PAYCELL,
        [EnumMember(Value = "PAYLANDS")] PAYLANDS,
        [EnumMember(Value = "PAYMOB")] PAYMOB,
        [EnumMember(Value = "PAYNET")] PAYNET,
        [EnumMember(Value = "PAYTABS")] PAYTABS,
        [EnumMember(Value = "PAYTR")] PAYTR,
        [EnumMember(Value = "QNB_PAY")] QNB_PAY,
        [EnumMember(Value = "REDSYS")] REDSYS,
        [EnumMember(Value = "RUBIK")] RUBIK,
        [EnumMember(Value = "SIPAY")] SIPAY,
        [EnumMember(Value = "STRIPE")] STRIPE,
        [EnumMember(Value = "TAMI")] TAMI,
        [EnumMember(Value = "TAP")] TAP,
        [EnumMember(Value = "TEB")] TEB,
        [EnumMember(Value = "TRPOS")] TRPOS,
        [EnumMember(Value = "VAKIFBANK")] VAKIFBANK,
        [EnumMember(Value = "VAKIFKATILIM")] VAKIFKATILIM,
        [EnumMember(Value = "WORLDPAY")] WORLDPAY,
        [EnumMember(Value = "YKB")] YKB,
        [EnumMember(Value = "ZIRAATBANK")] ZIRAATBANK,
        [EnumMember(Value = "ZIRAATBANK_INNOVA")] ZIRAATBANK_INNOVA,
        [EnumMember(Value = "ZIRAATKATILIM")] ZIRAATKATILIM,
        [EnumMember(Value = "BIN_PAY")] BIN_PAY
    }
}